myapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users/sign_in' => 'users#sign_in'
  post '/users/check_credentials' => 'users#check_credentials'
  get '/homepage' => 'users#homepage'
  get '/users/logout' => 'users#logout'
  get '/real_estate_companies/new' => 'real_estate_companies#new'
  get '/real_estate_companies' => 'real_estate_companies#index'
  post '/real_estate_companies/create' => 'real_estate_companies#create'
  root 'users#sign_in'
  get '/realtors/new' => 'realtors#new'
  post '/realtors/create' => 'realtors#create'
  get '/realtors/edit_company' => 'realtors#edit_company'
  post '/realtors/save_company' => 'realtors#save_company'
  get '/house_hunters/new' => 'house_hunters#new'
  post '/house_hunters/create' => 'house_hunters#create'
  get '/houses/new' => 'houses#new'
  post '/houses/create' => 'houses#create'
  get '/houses/index' => 'houses#index'
  get '/users/show_all' => 'users#show_all'
  get '/realtors' => 'realtors#index'
  get '/add_to_interest_list/:id' => 'houses#add_to_interest_list'
  get '/show_houses_with_filters/' => 'houses#show_houses_with_filters'
  get '/inquiries/new/:id' => 'inquiries#new'
  post '/inquiries/create' => 'inquiries#create'
  get '/inquiries/current_user_inquiries' => 'inquiries#current_user_inquiries'
  get 'houses/houses_posted_by_me' => 'houses#houses_posted_by_me'
  get 'houses/houses_posted_by_company' => 'houses#houses_posted_by_company'
  get '/show_potential_buyers/:id' => 'houses#show_potential_buyers'
  get '/inquiries/show_all_for_company' => 'inquiries#show_all_for_company'
  get '/inquiries/new_reply/:id' => 'inquiries#new_reply'
  post '/inquiries/create_reply/:id' => 'inquiries#create_reply'
  get '/users/reset_password_form' => 'users#reset_password_form'
  post '/users/reset_password' => 'users#reset_password'
  get '/houses/add_image_to_house/:id' => 'houses#add_image_to_house'
  post '/houses/upload_image/:id' => 'houses#upload_image'
  get '/houses/my_interest_list' => 'houses#my_interest_list'
  get '/houses/remove_from_interest_list/:id' => 'houses#remove_from_interest_list'
  get '/users/forgot_password_form' => 'users#forgot_password_form'
  post '/users/forgot_password' => 'users#forgot_password'
  resources :inquiries
  resources :admins
  resources :realtors
  resources :real_estate_companies
  resources :houses
end

myapp/app/controllers/houses_controller.rb
class HousesController < ApplicationController


  def show
    @house = House.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @house }
    end
  end

  def add_image_to_house
    @house = House.find(params[:id])
  end

  def upload_image
    @house = House.find(params[:id])
    puts @house
    puts image_params
    respond_to do |format|
      if @house.update_attributes(image_params)
        format.html {redirect_to '/homepage' , notice: 'Image is successfully uploaded.'}
      else
        render :edit
      end
      end
  end
  def edit
    @house = House.find(params[:id])
  end

  def destroy
    @house = House.find(params[:id])
    if  @house.destroy
    respond_to do |format|
      format.html { redirect_to '/houses/houses_posted_by_me' , notice: 'House was successfully deleted.' }
      format.json { head :no_content }
    end
    else
      redirect_to '/houses/houses_posted_by_me' , notice: 'Operation unsuccessful'
    end


  end

  def new
    @house = House.new
  end

  def houses_posted_by_me
    @houses = House.where(realtor_id: session[:id][0] ).order(created_at: :desc)
  end

  def my_interest_list
    @house_hunter_id = (session[:id][0] ).to_s
    sql = "select * from houses where id in ( select house_id from interest_lists where house_hunter_id = "+@house_hunter_id +" )"
    puts sql
    @houses = House.connection.select_all(sql)

  end

  def remove_from_interest_list
    @house_id = params[:id].to_s
    @house_hunter_id = (session[:id][0] ).to_s
    sql = "delete from interest_lists where house_hunter_id ="+@house_hunter_id+" and house_id = "+@house_id+" ;"
    @connection = ActiveRecord::Base.connection
    @result = @connection.exec_query(sql)
    if(@result)
      redirect_to '/houses/my_interest_list' , notice: 'House was successfully removed from interest list.'
    else
      redirect_to '/houses/my_interest_list' , notice: 'Error in removing from interest list.'
    end
  end
  def show_houses_with_filters
    @houses = House.all
  end
  def add_to_interest_list
    @house_hunter_id = session[:id]
    details = {house_hunter_id: @house_hunter_id[0], house_id: params[:id] }
    puts details
    @interest_list = InterestList.new(details)
    if  @interest_list.save
      redirect_to show_houses_with_filters_url , notice: 'House was successfully added to interest list.'
    else
      redirect_to show_houses_with_filters_url , notice: 'Already present in interest list.'
    end
  end

  def index
    @houses = House.all
    puts @houses
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @houses }
    end
  end
  def create
    @house = House.new(house_params)
    @realtor = Realtor.find_by(id: session[:id] )
    @house["real_estate_company_id"]  = @realtor["real_estate_company_id"]
    @house["realtor_id"]  = @realtor["id"]
    puts @house["real_estate_company_id"]
    puts @house["realtor_id"]
    if @house.save
      redirect_to  '/homepage' ,  notice: 'House was successfully posted.'
    else
      render 'new'
    end
  end

  def show_potential_buyers
    sql = "select * from house_hunters where id in ( select house_hunter_id from interest_lists where house_id = "+(params[:id].to_s) +" )"
    puts sql
    #Model.connection.select_all('sql').to_hash
    @house_hunters = HouseHunter.connection.select_all(sql).to_hash
    puts "data"
    puts @house_hunters

  end

  def houses_posted_by_company
    @realtor = Realtor.find_by(id: session[:id] )
    @houses = House.where(real_estate_company_id: @realtor["real_estate_company_id"] ).order(created_at: :desc)
  end


  def update
    @house = House.find(params[:id])
    respond_to do |format|
      if @house.update_attributes(house_params)
        format.html { redirect_to @house, notice: 'House was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def house_params
    params.require(:house).permit(:location,  :square_footage,  :year_built , :style , :price , :number_of_floors, :basement, :current_house_owner, :contact_info_of_realtor)
  end

  def image_params
    params.require(:house).permit(:file_name)
  end
end

myapp/app/helpers/houses_helper.rb
module HousesHelper
end

myapp/app/views/houses/add_image_to_house.html.erb
<h1>Uploading image for a house</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Location :</b>
  <%= @house.location %>
</p>

<p>
  <b>Square footage</b>
  <%= @house.square_footage %>
</p>

<p>
  <b>Year built</b>
  <%= @house.year_built %>
</p>

<p>
  <b>Style</b>
  <%= @house.style %>
</p>

<p>
  <b>Price</b>
  <%= @house.price %>
</p>

<p>
  <b>Number of floors</b>
  <%= @house.number_of_floors %>
</p>

<p>
  <b>Basement</b>
  <%= @house.basement %>
</p>

<p>
  <b>Current house owner</b>
  <%= @house.current_house_owner %>
</p>

<p>
  <b>Contact information of realtor</b>
  <%= @house.contact_info_of_realtor %>
</p>

<%= form_with url: "/houses/upload_image/"+@house.id.to_s , scope: :house do |form| %>
<div>
  <%= form.label :file_name %>
  <%= form.file_field :file_name %>
</div>
  <br>
  <br>
  <%= submit_tag("Upload") %>
  <%end %>

<br>
<br>
<%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/houses/edit.html.erb
<h1> Edit a house </h1>

<%= form_with url: "/houses/"+(@house.id).to_s , scope: :house , method: 'PATCH' , local: true do |form| %>

  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@house.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @house.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <%= form.label :location %>
  <%= form.text_area :location %>
  <br>
  <br>
  <%= form.label :square_footage %>
  <%= form.text_field :square_footage %>
  <br>
  <br>
  <%= form.label :year_built %>
  <%= form.text_field :year_built %>
  <br>
  <br>
  <%= form.label :style %>
  <%= form.text_field :style %>
  <br>
  <br>
  <%= form.label :price %>
  <%= form.text_field :price %>
  <br>
  <br>
  <%= form.label :number_of_floors %>
  <%= form.text_field :number_of_floors %>
  <br>
  <br>
  <%= form.label :basement %> :::::::::
  <%= form.label :yes %>
  <%= form.radio_button :basement, 'yes', :checked => true %>
  <%= form.label :no %>
  <%= form.radio_button :basement, 'no' %>
  <br>
  <br>
  <%= form.label :current_house_owner %>
  <%= form.text_area :current_house_owner %>
  <br>
  <br>
  <%= form.label :contact_info_of_realtor %>
  <%= form.text_area :contact_info_of_realtor %>
  <br>
  <br>

  <br>
  <%= submit_tag("Update") %>
<% end %>

myapp/app/views/houses/houses_posted_by_company.html.erb
<h1>Houses posted by my company</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Location</th>
    <th>Square footage</th>
    <th>Year built</th>
    <th>Style</th>
    <th>Price</th>
    <th>Number of floors </th>
    <th>Basement</th>
    <th>Current house owner</th>
    <th>Contact information of realtor</th>
    <th></th>
  </tr>

  <% if !@houses.nil? then @houses.each do |house| %>
      <tr>
        <td><%= house.location %></td>
        <td><%= house.square_footage %></td>
        <td><%= house.year_built %></td>
        <td><%= house.style %></td>
        <td><%= house.price %></td>
        <td><%= house.number_of_floors %></td>
        <td><%= house.basement %></td>
        <td><%= house.current_house_owner %></td>
        <td><%= house.contact_info_of_realtor %></td>
        <td><%= link_to 'Show', house %> || </td>
        <td><%= link_to 'Show potential buyers', "/show_potential_buyers/" +house.id.to_s %> ||</td>
        <td><%= link_to "Upload images to the house",  ' /houses/add_image_to_house/'+house.id.to_s %>  </td>
      </tr>

    <% end %>
  <% end %>
</table>
<br />

<%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/houses/houses_posted_by_me.html.erb
<h1>Houses posted by me</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Location</th>
    <th>Square footage</th>
    <th>Year built</th>
    <th>Style</th>
    <th>Price</th>
    <th>Number of floors </th>
    <th>Basement</th>
    <th>Current house owner</th>
    <th>Contact information of realtor</th>
    <th></th>
  </tr>

  <% if !@houses.nil? then @houses.each do |house| %>
      <tr>
        <td><%= house.location %></td>
        <td><%= house.square_footage %></td>
        <td><%= house.year_built %></td>
        <td><%= house.style %></td>
        <td><%= house.price %></td>
        <td><%= house.number_of_floors %></td>
        <td><%= house.basement %></td>
        <td><%= house.current_house_owner %></td>
        <td><%= house.contact_info_of_realtor %></td>

        <td><%= link_to 'Show', house %> || </td>
        <td><%= link_to "Upload images to the house",  ' /houses/add_image_to_house/'+house.id.to_s %> || </td>
        <td><%= link_to 'Edit', edit_house_url(house) %> || </td>
        <td><%= link_to 'Delete', house, method: :delete, data: { confirm: 'Are you sure?' }  %></td>

      </tr>
    <% end %>
  <% end %>
</table>

<br />

<%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/houses/index.html.erb
<h1>All houses</h1>

<table>
  <tr>
    <th>Location</th>
    <th>Square footage</th>
    <th>Year built</th>
    <th>Style</th>
    <th>Price</th>
    <th>Number of floors </th>
    <th>Basement</th>
    <th>Current house owner</th>
    <th>Contact information of realtor</th>
    <th></th>
  </tr>

  <% if !@houses.nil? then @houses
      .each do |house| %>
      <tr>
        <td><%= house.location %></td>
        <td><%= house.square_footage %></td>
        <td><%= house.year_built %></td>
        <td><%= house.style %></td>
        <td><%= house.price %></td>
        <td><%= house.number_of_floors %></td>
        <td><%= house.basement %></td>
        <td><%= house.current_house_owner %></td>
        <td><%= house.contact_info_of_realtor %></td>
        <td><%= link_to 'Show', house %>  </td>
      </tr>
    <% end %>
  <% end %>
</table>

<br />

<%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/houses/my_interest_list.html.erb
<head>
  <style>
    #notice {
      color: red;
      font-size: large;
    }

  </style>
</head>
<h1>My interest list</h1>
<br>
<br>
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>Location</th>
    <th>Square footage</th>
    <th>Year built</th>
    <th>Style</th>
    <th>Price</th>
    <th>Number of floors </th>
    <th>Basement</th>
    <th>Current house owner</th>
    <th>Contact information of realtor</th>
    <th></th>
  </tr>

  <% if !@houses.nil? then @houses
      .each do |house| %>
      <tr>
        <td><%= house["location"] %></td>
        <td><%= house["square_footage"] %></td>
        <td><%= house["year_built"]%></td>
        <td><%= house["style"] %></td>
        <td><%= house["price"] %></td>
        <td><%= house["number_of_floors"] %></td>
        <td><%= house["basement"] %></td>
        <td><%= house["current_house_owner"] %></td>
        <td><%= house["contact_info_of_realtor"] %></td>
        <td><%= link_to 'Show', house["id"].to_s %> ||  </td>
        <td><%= link_to 'Remove from interest list','/houses/remove_from_interest_list/'+ house["id"].to_s %>  </td>
      </tr>
    <% end %>
  <% end %>
</table>

<br />

<%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/houses/new.html.erb
<h1> List a house </h1>

<%= form_with url: "/houses/create" , scope: :house , local: true do |form| %>

  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@house.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @house.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br>
  <%= form.label :location %>
  <%= form.text_area :location %>
  <br>
  <br>
  <br>
  <%= form.label :square_footage %>
  <%= form.text_field :square_footage %>
  <br>
  <br>
  <%= form.label :year_built %>
  <%= form.text_field :year_built %>
  <br>
  <br>
  <%= form.label :style %>
  <%= form.text_field :style %>
  <br>
  <br>
  <%= form.label :price %>
  <%= form.text_field :price %>
  <br>
  <br>
  <%= form.label :number_of_floors %>
  <%= form.text_field :number_of_floors %>
  <br>
  <br>
  <%= form.label :basement %> :::::::::
  <%= form.label :yes %>
  <%= form.radio_button :basement, 'yes', :checked => true %>
  <%= form.label :no %>
  <%= form.radio_button :basement, 'no' %>
  <br>
  <br>
  <%= form.label :current_house_owner %>
  <%= form.text_area :current_house_owner %>
  <br>
  <br>
  <%= form.label :contact_info_of_realtor %>
  <%= form.text_area :contact_info_of_realtor %>
  <br>
  <br>
  <br>
  <%= submit_tag("Post the house") %>
  <br>
  <br>
  <%= link_to 'Go back to homepage', '/homepage' %> |
<% end %>

myapp/app/views/houses/show.html.erb
<h1>Showing house</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Location :</b>
  <%= @house.location %>
</p>

<p>
  <b>Square footage</b>
  <%= @house.square_footage %>
</p>

<p>
  <b>Year built</b>
  <%= @house.year_built %>
</p>

<p>
  <b>Style</b>
  <%= @house.style %>
</p>

<p>
  <b>Price</b>
  <%= @house.price %>
</p>

<p>
  <b>Number of floors</b>
  <%= @house.number_of_floors %>
</p>

<p>
  <b>Basement</b>
  <%= @house.basement %>
</p>

<p>
  <b>Current house owner</b>
  <%= @house.current_house_owner %>
</p>

<p>
  <b>Contact information of realtor</b>
  <%= @house.contact_info_of_realtor %>
</p>

<br>
<br>
<%= image_tag(@house.file_name.url, alt: 'Image') if @house.file_name? %>

<br>
<br>
<%= link_to 'Go back to homepage ', homepage_path %>
<br>

myapp/app/views/houses/show_houses_with_filters.html.erb
<head>
  <style>
    #notice {
      color: green;
      font-size: large;
    }

  </style>
</head>
<h1>All houses</h1>
<br>
<br>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Location</th>
    <th>Square footage</th>
    <th>Year built</th>
    <th>Style</th>
    <th>Price</th>
    <th>Number of floors </th>
    <th>Basement</th>
    <th>Current house owner</th>
    <th>Contact information of realtor</th>
    <th></th>
  </tr>

  <% if !@houses.nil? then @houses.each do |house| %>
      <tr>
        <td><%= house.location %></td>
        <td><%= house.square_footage %></td>
        <td><%= house.year_built %></td>
        <td><%= house.style %></td>
        <td><%= house.price %></td>
        <td><%= house.number_of_floors %></td>
        <td><%= house.basement %></td>
        <td><%= house.current_house_owner %></td>
        <td><%= house.contact_info_of_realtor %></td>
        <td><%= link_to 'Show', house %> || </td>
        <td><%= link_to 'Add to Interest List', "/add_to_interest_list/"+(house.id.to_s) %> || </td>
        <td><%= link_to 'Inquiry', "/inquiries/new/"+(house.id.to_s) %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<br />

<%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/houses/show_potential_buyers.html.erb
<h1> Potential buyers </h1>
<br>
<br>
<table>
  <tr>
    <th>Name || </th>
    <th>Email || </th>
    <th>Phone || </th>
    <th>Preferred contact method || </th>


  </tr>

  <% if !@house_hunters.nil? then @house_hunters.each do |househunter| %>

      <tr>
        <td><%= househunter["name"] %></td>
        <td><%= househunter["email"] %></td>
        <td><%= househunter["phone"] %></td>
        <td><%= househunter["contact_method"] %></td>


      </tr>
      <% end %>

    <% end %>


</table>
<br />
<br />
<br />

<%= link_to 'Go back to homepage ', homepage_path %>