myapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users/sign_in' => 'users#sign_in'
  post '/users/check_credentials' => 'users#check_credentials'
  get '/homepage' => 'users#homepage'
  get '/users/logout' => 'users#logout'
  get '/real_estate_companies/new' => 'real_estate_companies#new'
  get '/real_estate_companies' => 'real_estate_companies#index'
  post '/real_estate_companies/create' => 'real_estate_companies#create'
  root 'users#sign_in'
  get '/realtors/new' => 'realtors#new'
  post '/realtors/create' => 'realtors#create'
  get '/realtors/edit_company' => 'realtors#edit_company'
  post '/realtors/save_company' => 'realtors#save_company'
  get '/house_hunters/new' => 'house_hunters#new'
  post '/house_hunters/create' => 'house_hunters#create'
  get '/houses/new' => 'houses#new'
  post '/houses/create' => 'houses#create'
  get '/houses/index' => 'houses#index'
  get '/users/show_all' => 'users#show_all'
  get '/realtors' => 'realtors#index'
  get '/add_to_interest_list/:id' => 'houses#add_to_interest_list'
  get '/show_houses_with_filters/' => 'houses#show_houses_with_filters'
  get '/inquiries/new/:id' => 'inquiries#new'
  post '/inquiries/create' => 'inquiries#create'
  get '/inquiries/current_user_inquiries' => 'inquiries#current_user_inquiries'
  get 'houses/houses_posted_by_me' => 'houses#houses_posted_by_me'
  get 'houses/houses_posted_by_company' => 'houses#houses_posted_by_company'
  get '/show_potential_buyers/:id' => 'houses#show_potential_buyers'
  get '/inquiries/show_all_for_company' => 'inquiries#show_all_for_company'
  get '/inquiries/new_reply/:id' => 'inquiries#new_reply'
  post '/inquiries/create_reply/:id' => 'inquiries#create_reply'
  get '/users/reset_password_form' => 'users#reset_password_form'
  post '/users/reset_password' => 'users#reset_password'
  get '/houses/add_image_to_house/:id' => 'houses#add_image_to_house'
  post '/houses/upload_image/:id' => 'houses#upload_image'
  get '/houses/my_interest_list' => 'houses#my_interest_list'
  get '/houses/remove_from_interest_list/:id' => 'houses#remove_from_interest_list'
  get '/users/forgot_password_form' => 'users#forgot_password_form'
  post '/users/forgot_password' => 'users#forgot_password'
  resources :inquiries
  resources :admins
  resources :realtors
  resources :real_estate_companies
  resources :houses
end

myapp/app/models/real_estate_company.rb
class RealEstateCompany < ApplicationRecord
  validates :company_name, uniqueness:  true, presence: true
  validates :website, presence: true
  validates :address,  presence: true
  validates :size_of_company,   presence: true
  validates :founded_year,   presence: true
  validates :revenue,   presence: true
  validates :synopsis,   presence: true
end

myapp/app/controllers/real_estate_companies_controller.rb
class RealEstateCompaniesController < ApplicationController


  def new
   @company = RealEstateCompany.new
  end

  def create
    @company = RealEstateCompany.new(company_params)
    if @company.save
      if(session[:user_type] == "realtor")
        @realtor = Realtor.find_by(id: session[:id])
        @realtor["real_estate_company_id"] = @company.id
        @realtor.save
        redirect_to '/homepage' , notice: 'Company was successfully created and added to your profile .'
      else
        redirect_to '/homepage'
      end
    else
      render 'new'
    end
  end

  def index
    @companies = RealEstateCompany.all
    puts @companies
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  def edit
    @company = RealEstateCompany.find(params[:id])
  end

  def update
    @company = RealEstateCompany.find(params[:id])
    respond_to do |format|
      if @company.update_attributes(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company = RealEstateCompany.find(params[:id])
    @company.destroy
    respond_to do |format|
      format.html { redirect_to real_estate_companies_url , notice: 'Company was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  def show
    @company = RealEstateCompany.find(params[:id])
    puts @company.company_name
    puts @company.website
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end



  private
  def company_params
    params.require(:company).permit(:company_name,  :website,  :address,  :size_of_company,  :founded_year, :revenue,  :synopsis)
  end
end

myapp/app/helpers/real_estate_companies_helper.rb
module RealEstateCompaniesHelper
end

myapp/app/views/real_estate_companies/edit.html.erb
<h1>Editing Real estate company</h1>

<% if @company.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@company.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with url: "/real_estate_companies/"+(@company.id).to_s,  scope: :company , method: 'PATCH' , local: true  do |form| %>

  <%= form.label :company_name %>
  <%= form.text_field :company_name %>
  <br>
  <br>
  <%= form.label :website %>
  <%= form.text_field :website %>
  <br>
  <br>
  <%= form.label :address %>
  <%= form.text_area :address %>
  <br>
  <br>
  <%= form.label :size_of_company %>
  <%= form.text_field :size_of_company %>
  <br>
  <br>
  <%= form.label :founded_year %>
  <%= form.text_field :founded_year %>
  <br>
  <br>
  <%= form.label :revenue %>
  <%= form.text_field :revenue %>
  <br>
  <br>
  <%= form.label :synopsis %>
  <%= form.text_area :synopsis %>

  <br>

  <br>


  <br>
  <%= submit_tag("Update") %>
  <br>
  <br>
  <%= link_to 'Go back to homepage', '/homepage' %> |
<% end %>

myapp/app/views/real_estate_companies/index.html.erb
<h1>Listing Real estate companies</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th> Company name </th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% if !@companies.nil? then @companies.each do |company| %>
      <tr>
        <td><%= company.company_name %></td>
        <td><%= link_to 'Show', company %></td>
        <% if session[:user_type] =="admin"%>
        <td><%= link_to 'Edit', edit_real_estate_company_path(company) %></td>
        <td><%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
          <%end %>
      </tr>
    <% end %>
  <% end %>
</table>

<br />

    <%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/real_estate_companies/new.html.erb
<h1> --------Create Real estate Company----- </h1>

<% if @company.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@company.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with url: "/real_estate_companies/create" , scope: :company ,  local: true do |form| %>

  <br>
  <%= form.label :company_name %>
  <%= form.text_field :company_name %>
  <br>
  <br>
  <%= form.label :website %>
  <%= form.text_field :website %>
  <br>
  <br>
  <%= form.label :address %>
  <%= form.text_area :address %>
  <br>
  <br>
  <%= form.label :size_of_company %>
  <%= form.text_field :size_of_company %>
  <br>
  <br>
  <%= form.label :founded_year %>
  <%= form.text_field :founded_year %>
  <br>
  <br>
  <%= form.label :revenue %>
  <%= form.text_field :revenue %>
  <br>
  <br>
  <%= form.label :synopsis %>
  <%= form.text_area :synopsis %>

  <br>
  <br>
  <br>
  <%= submit_tag("Create company") %>
  <br />
  <br>
  <br>
  <%= link_to 'Go back to homepage', '/homepage' %> |
<% end %>

myapp/app/views/real_estate_companies/show.html.erb
<h1>Listing Real estate companies</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Company name :</b>
  <%= @company.company_name %>
</p>

<p>
  <b>Website</b>
  <%= @company.website %>
</p>

<p>
  <b>Address</b>
  <%= @company.address %>
</p>
<p>
  <b>Size of company</b>
  <%= @company.size_of_company %>
</p>
<p>
  <b>Founded year</b>
  <%= @company.founded_year %>
</p>
<p>
  <b>Revenue</b>
  <%= @company.revenue %>
</p>
<p>
  <b>Synopsis</b>
  <%= @company.synopsis %>
</p>


<br />

<%= link_to 'Go back to homepage', '/homepage' %> |
<br>
<% if session[:user_type] =="admin"%>
<%= link_to 'Edit', edit_real_estate_company_path(@company) %> |
<%end %>