myapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users/sign_in' => 'users#sign_in'
  post '/users/check_credentials' => 'users#check_credentials'
  get '/homepage' => 'users#homepage'
  get '/users/logout' => 'users#logout'
  get '/real_estate_companies/new' => 'real_estate_companies#new'
  get '/real_estate_companies' => 'real_estate_companies#index'
  post '/real_estate_companies/create' => 'real_estate_companies#create'
  root 'users#sign_in'
  get '/realtors/new' => 'realtors#new'
  post '/realtors/create' => 'realtors#create'
  get '/realtors/edit_company' => 'realtors#edit_company'
  post '/realtors/save_company' => 'realtors#save_company'
  get '/house_hunters/new' => 'house_hunters#new'
  post '/house_hunters/create' => 'house_hunters#create'
  get '/houses/new' => 'houses#new'
  post '/houses/create' => 'houses#create'
  get '/houses/index' => 'houses#index'
  get '/users/show_all' => 'users#show_all'
  get '/realtors' => 'realtors#index'
  get '/add_to_interest_list/:id' => 'houses#add_to_interest_list'
  get '/show_houses_with_filters/' => 'houses#show_houses_with_filters'
  get '/inquiries/new/:id' => 'inquiries#new'
  post '/inquiries/create' => 'inquiries#create'
  get '/inquiries/current_user_inquiries' => 'inquiries#current_user_inquiries'
  get 'houses/houses_posted_by_me' => 'houses#houses_posted_by_me'
  get 'houses/houses_posted_by_company' => 'houses#houses_posted_by_company'
  get '/show_potential_buyers/:id' => 'houses#show_potential_buyers'
  get '/inquiries/show_all_for_company' => 'inquiries#show_all_for_company'
  get '/inquiries/new_reply/:id' => 'inquiries#new_reply'
  post '/inquiries/create_reply/:id' => 'inquiries#create_reply'
  get '/users/reset_password_form' => 'users#reset_password_form'
  post '/users/reset_password' => 'users#reset_password'
  get '/houses/add_image_to_house/:id' => 'houses#add_image_to_house'
  post '/houses/upload_image/:id' => 'houses#upload_image'
  get '/houses/my_interest_list' => 'houses#my_interest_list'
  get '/houses/remove_from_interest_list/:id' => 'houses#remove_from_interest_list'
  get '/users/forgot_password_form' => 'users#forgot_password_form'
  post '/users/forgot_password' => 'users#forgot_password'
  resources :inquiries
  resources :admins
  resources :realtors
  resources :real_estate_companies
  resources :houses
end

myapp/app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :subject, presence: true
  validates :message_content,  presence: true
end

myapp/app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @house_id = params[:id]
    @house_hunter_id = session[:id][0]
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      redirect_to homepage_url , notice: 'Inquiry was successfully sent'
    else
      @house_id = @inquiry["house_id"]
      @house_hunter_id = @inquiry["house_hunter_id"]
      render 'new'
    end
    end


    def new_reply
      @inquiry_id = params[:id]
      @inquiry = Inquiry.find(@inquiry_id)
      @reply = ReplyToInquiry.new

    end

    def create_reply
      @reply = ReplyToInquiry.new(reply_params)
      @inquiry_id = params[:id]
      @reply["inquiry_id"] = @inquiry_id
        if @reply.save
         redirect_to "/inquiries/show_all_for_company" , notice: 'Reply for the inquiry was successfully sent'
        else
          redirect_to '/inquiries/new_reply/'+ @inquiry_id.to_s , notice: 'Please enter the reply !!!'
        end
    end




  def show_all_for_company
    @realtor = Realtor.find_by(id: session[:id] )
    @real_estate_company_id  = (@realtor["real_estate_company_id"]).to_s
    sql = "select * from inquiries where house_id in ( select house_id from houses where real_estate_company_id = "+@real_estate_company_id +" )"
    puts sql
    #Model.connection.select_all('sql').to_hash
    @inquiries = Inquiry.connection.select_all(sql).to_hash
  end


  def index
    @inquiries = Inquiry.all
    puts @inquiries
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inquiries }
    end
  end

  def current_user_inquiries
    @inquiries = Inquiry.where(house_hunter_id: session[:id][0] ).order(created_at: :desc)
    puts @inquiries
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @inquiries }
    end
  end

  def edit
    @inquiry = Inquiry.find(params[:id])
  end

  def update
    @inquiry = Inquiry.find(params[:id])
    respond_to do |format|
      if @inquiry.update_attributes(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inquiry = Inquiry.find(params[:id])
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to '/inquiries/current_user_inquiries' , notice: 'Inquiry was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  def show
    @inquiry = Inquiry.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @inquiry }
    end
  end




  private
  def inquiry_params
    params.require(:inquiry).permit(:house_id,  :message_content,  :subject , :house_hunter_id )
  end

    def reply_params
      params.require(:reply).permit(:reply )
    end

  end

myapp/app/helpers/inquiries_helper.rb
module InquiriesHelper
end

myapp/app/views/inquiries/current_user_inquiries.html.erb
<h1>My Inquiries</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th> Subject </th>
    <th>  Message content </th>
    <th></th>
    <th></th>
  </tr>

  <% if !@inquiries.nil? then @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.subject %></td>
        <td><%= inquiry.message_content %></td>
        <td><%= link_to 'Show', inquiry %></td>
        <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
        <td><%= link_to 'Delete', inquiry, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<br />

<%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/inquiries/edit.html.erb
<h1>--------Editing Inquiry------------</h1>

<br>
<% if @inquiry.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@inquiry.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<br>
<%= form_with url: "/inquiries/"+(@inquiry.id).to_s,  scope: :inquiry , method: 'PATCH' , local: true do |form| %>

  <%= form.label :subject %>
  <%= form.text_field :subject %>
  <br>
  <br>
  <%= form.label :message_content %>
  <%= form.text_area :message_content %>
  <br>
  <br>

  <br>


  <br>
  <%= submit_tag("Update") %>
<% end %>

myapp/app/views/inquiries/index.html.erb
<h1>All Inquiries</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th> Subject </th>
    <th>  Message content </th>
    <th></th>
    <th></th>
  </tr>

  <% if !@inquiries.nil? then @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.subject %></td>
        <td><%= inquiry.message_content %></td>
        <td><%= link_to 'Show', inquiry %></td>
          <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
          <td><%= link_to 'Delete', inquiry, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<br />

<%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/inquiries/new.html.erb
<h1>---- Create an inquiry ----</h1>
<br>
<% if @inquiry.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@inquiry.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<br>
<p id="notice"><%= notice %></p>
<%= form_with url: "/inquiries/create" , scope: :inquiry, local: true do |form| %>
  <%= form.hidden_field :house_id , :value => @house_id %>
  <%= form.hidden_field :house_hunter_id , :value => @house_hunter_id %>
<br>
  <%= form.label :subject %>
  <%= form.text_field :subject %>
  <br>
  <br>
  <%= form.label :message_content %>
  <%= form.text_area :message_content %>
  <br>
  <br>
  <br>
  <%= submit_tag("Submit") %>
<% end %>
<br>
<br>
<br>
<%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/inquiries/new_reply.html.erb
<head>
  <style>
    #notice {
      color: red;
      font-size: large;
    }
    #main {
      text-indent: 30px;
      color: darkblue;
    }
  </style>
</head>
<h1>New Reply for the inquiry</h1>

<p id="notice"><%= notice %></p>
<%= form_with url: '/inquiries/create_reply/'+@inquiry.id.to_s , scope: :reply do |form| %>
<p>
  <b>Subject :</b>
  <%= @inquiry.subject %>
</p>

<p>
  <b>Message content</b>
  <%= @inquiry.message_content %>
</p>

  <br>
  <b>
<%= form.label :reply %>
  </b>
<%= form.text_area :reply %>

  <br>
  <br>
  <%= submit_tag("Create reply") %>
<br>
  <br />
<%= link_to 'Go back ', '/inquiries/show_all_for_company' %>

<%end %>

myapp/app/views/inquiries/show.html.erb
<head>
  <style>
    #notice {
      color: red;
      font-size: large;
    }
    #main {
      text-indent: 30px;
      color: darkblue;
    }
  </style>
</head>
<h1>Showing inquiry</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Subject :</b>
  <%= @inquiry.subject %>
</p>

<p>
  <b>Message content</b>
  <%= @inquiry.message_content %>
</p>



<br>

  <%= link_to 'Edit',  edit_inquiry_path(@inquiry) %>

<br>
<br>

<%= link_to 'Go back to homepage', '/homepage' %> |

myapp/app/views/inquiries/show_all_for_company.html.erb
<h1>All Inquiries for my company</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th> Subject </th>
    <th>  Message content </th>
    <th></th>
    <th></th>
  </tr>

  <% if !@inquiries.nil? then @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry["subject"] %></td>
        <td><%= inquiry["message_content"] %></td>
        <td><%= link_to 'Reply to the inquiry', '/inquiries/new_reply/'+inquiry["id"].to_s %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<br />

<%= link_to 'Go back to homepage ', homepage_path %>