myapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users/sign_in' => 'users#sign_in'
  post '/users/check_credentials' => 'users#check_credentials'
  get '/homepage' => 'users#homepage'
  get '/users/logout' => 'users#logout'
  get '/real_estate_companies/new' => 'real_estate_companies#new'
  get '/real_estate_companies' => 'real_estate_companies#index'
  post '/real_estate_companies/create' => 'real_estate_companies#create'
  root 'users#sign_in'
  get '/realtors/new' => 'realtors#new'
  post '/realtors/create' => 'realtors#create'
  get '/realtors/edit_company' => 'realtors#edit_company'
  post '/realtors/save_company' => 'realtors#save_company'
  get '/house_hunters/new' => 'house_hunters#new'
  post '/house_hunters/create' => 'house_hunters#create'
  get '/houses/new' => 'houses#new'
  post '/houses/create' => 'houses#create'
  get '/houses/index' => 'houses#index'
  get '/users/show_all' => 'users#show_all'
  get '/realtors' => 'realtors#index'
  get '/add_to_interest_list/:id' => 'houses#add_to_interest_list'
  get '/show_houses_with_filters/' => 'houses#show_houses_with_filters'
  get '/inquiries/new/:id' => 'inquiries#new'
  post '/inquiries/create' => 'inquiries#create'
  get '/inquiries/current_user_inquiries' => 'inquiries#current_user_inquiries'
  get 'houses/houses_posted_by_me' => 'houses#houses_posted_by_me'
  get 'houses/houses_posted_by_company' => 'houses#houses_posted_by_company'
  get '/show_potential_buyers/:id' => 'houses#show_potential_buyers'
  get '/inquiries/show_all_for_company' => 'inquiries#show_all_for_company'
  get '/inquiries/new_reply/:id' => 'inquiries#new_reply'
  post '/inquiries/create_reply/:id' => 'inquiries#create_reply'
  get '/users/reset_password_form' => 'users#reset_password_form'
  post '/users/reset_password' => 'users#reset_password'
  get '/houses/add_image_to_house/:id' => 'houses#add_image_to_house'
  post '/houses/upload_image/:id' => 'houses#upload_image'
  get '/houses/my_interest_list' => 'houses#my_interest_list'
  get '/houses/remove_from_interest_list/:id' => 'houses#remove_from_interest_list'
  get '/users/forgot_password_form' => 'users#forgot_password_form'
  post '/users/forgot_password' => 'users#forgot_password'
  resources :inquiries
  resources :admins
  resources :realtors
  resources :real_estate_companies
  resources :houses
end

myapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def sign_in
  end

  def forgot_password_form
  end

  def forgot_password
    @my_params = forgot_password_params
    puts @my_params
    if @my_params["usertype"] == "realtor"
      @table_name = Realtor
    else
      @table_name = HouseHunter
    end

    if(@table_name.exists?(email:@my_params["email"]))
      @user = @table_name.find_by(email: @my_params["email"])
      if(@user.secret_question== @my_params["secret_question"])
       if  @user.update_attributes(password: @my_params["password"])
          redirect_to root_path , notice: 'Password has been successfully changed. Kindly login '
        else
          redirect_to "/users/forgot_password_form"  , notice: 'Unable to process your request.'
        end
      else
        redirect_to "/users/forgot_password_form"  , notice: 'Given secret question answer doesnot matches our records .'
      end
    else
      redirect_to ".users/forgot_password_form" , notice: 'Given email doesnot matches our records .'
    end
  end

  def reset_password
    @user_type = session[:user_type]
    puts @user_type
    if(@user_type == "realtor")
      @table_name = Realtor
    elsif (@user_type == "househunter")
      @table_name = HouseHunter
    elsif(@user_type =="admin")
      @table_name = Admin
    end
    respond_to do |format|
      @params = reset_password_params
      puts @params
      if @params["new_password"] == @params["confirm_new_password"]
        @user = @table_name.find(session[:id][0])
        if(@user["password"] == @params["old_password"])
           if @user.update_attributes(password: @params["new_password"])
                format.html { redirect_to "/homepage", notice: 'Your password is successfully reset' }
           else
             redirect_to "/users/reset_password_form",notice: "Unable to process the change ! Contact system admin"
             end
        else
          format.html { redirect_to "/users/reset_password_form", notice: "Old password doesn't match our records" }
        end

      else
        format.html { redirect_to "/users/reset_password_form", notice: "New password and confirm new password doesn't match" }
      end
    end
  end

  def reset_password_form
  end
  def homepage
    @realtor = Realtor.find(session[:id][0])
    if(@realtor.real_estate_company_id.nil?)
      @real_estate_company_id = -1
    else
      @real_estate_company_id = RealEstateCompany.find(@realtor.real_estate_company_id)
    end

  end

  def logout
    reset_session
    redirect_to '/users/sign_in' , notice: 'You have been successfully logged out !'
  end

  def show_all
    @realtor = Realtor.all
    @househunter = HouseHunter.all

  end

  def show_realtor
    @realtor = Realtor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @realtor }
    end
  end

  def check_credentials
    puts "entered"
    @email = params[:email]
    @password = params[:password]
    @user_type = params[:usertype]
    session[:email] = @email
    session[:user_type] = @user_type
    puts @user_type
    if request.post? and params[:email]

      if(@user_type == "realtor")
        @table_name = Realtor
      elsif (@user_type == "househunter")
        @table_name = HouseHunter
      elsif(@user_type =="admin")
        @table_name = Admin
      end
      puts @table_name.exists?(email: @email)

      if(@table_name.exists?(email: @email))
        @passwordInDB =  @table_name.where(email: @email).pluck(:password)
        puts "email present"
        if (@passwordInDB[0] == @password)
            redirect_to action: "homepage"
        else
          redirect_to root_url , notice: 'Wrong user credentials'
          end
          session[:id] = @table_name.where(email: @email).pluck(:id)
          session[:name] = @table_name.where(email: @email).pluck(:name)
        else
          redirect_to root_url , notice: 'Wrong user credentials'
        end
      end
  end

  private
  def reset_password_params
    params.require(:user).permit(:old_password, :confirm_new_password , :new_password)
  end

  def forgot_password_params
    params.require(:user).permit(:email, :secret_question, :password , :usertype)
  end
  end

myapp/app/helpers/users_helper.rb
module UsersHelper
end

myapp/app/views/users/_banner.html.erb
<div style="text-align:center"><h1> HouseHunting.com</h1></div>
<br>
<br>

myapp/app/views/users/_header.html.erb
<div style="text-align:center"><h2> Welcome : <%= session[:name][0] %>  </h2> </div>
<div style="text-align:right"><h3><%= link_to "Logout", '/users/logout' %></h3></div>

<br>

<br>
<br>

myapp/app/views/users/_househunter.html.erb
<table>
  <tr>
    <th> Name </th>
    <th>Email </th>
    <th>Phone</th>
    <th>Preferred contact method</th>
    <th>User type </th>

  </tr>

  <% if !@househunter.nil? then @househunter.each do |househunter| %>
      <tr>
        <td><%= househunter.name %></td>
        <td><%= househunter.email %></td>
        <td><%= househunter.phone %></td>
        <td><%= househunter.contact_method %></td>
        <td> House Hunter </td>



      </tr>
    <% end %>
  <% end %>
</table>

<br />

<%= link_to 'Go back to homepage ', homepage_path %>

myapp/app/views/users/_realtor.html.erb
<table>
  <tr>
    <th> Name </th>
    <th>Email </th>
    <th>Phone</th>
    <th>User type </th>
    <th></th>

  </tr>

  <% if !@realtor.nil? then @realtor.each do |realtor| %>
      <tr>
        <td><%= realtor.name %></td>
        <td><%= realtor.email %></td>
        <td><%= realtor.phone %></td>
        <td> Realtor </td>
      </tr>
    <% end %>
  <% end %>
</table>

<br />

myapp/app/views/users/forgot_password_form.html.erb
<head>
  <style>
    #notice {
      color: red;
      font-size: large;
    }
  </style>
</head>
<h1>---- Forgot password ----</h1>
<br>
<p id="notice"><%= notice %></p>
<br>
<%= form_with url: "/users/forgot_password" , scope: :user do |form| %>
  <br>
  <%= form.label :email %>
  <%= form.text_field :email %>
  <br>
  <br>
  <%= form.label :what_is_your_first_pet_name_? %>
  <%= form.text_field :secret_question %>
  <br>
  <br>
  <%= form.label :new_password %>
  <%= form.password_field :password %>
  <br>
  <br>
  <br>
  <%= form.radio_button :usertype, 'realtor', :checked => true %>
  <%= form.label :realtor %>
  <%= form.radio_button :usertype, 'househunter' %>
  <%= form.label :house_hunter %>
  <br>
  <br>
  <%= submit_tag("Submit") %>
  <br>
  <br>
  <%= link_to "Go back ", root_url %>
<% end %>

myapp/app/views/users/homepage.html.erb
<head>
  <style>
    #notice {
      color: red;
      font-size: large;
    }

  </style>
</head>
<%= render "banner" %>
<%= render "header" %>
<p id="notice"><%= notice %></p>

<% if session[:user_type] =="admin"%>

  <%= link_to "Create real estate company ", '/real_estate_companies/new' %>
  <br>
  <br>
  <%= link_to "View all users ", '/users/show_all' %>
  <br>

  <br>
  <%= link_to "Edit profile ",  edit_admin_url(session[:id][0]) %>
  <br>
  <br>
  <%= link_to "Show realtors ", '/realtors' %>
  <br>
  <%= link_to "Show real estate companies ", '/real_estate_companies' %>
  <br>
  <%= link_to "View all houses ", houses_url %>
  <br>
  <br>
  <%= link_to "Create House Hunters", 'house_hunters/new' %>
  <br>
  <br>
  <%= link_to "Create Realtors", 'realtors/new' %>
  <br>
  <br>
  <%= link_to "View all inquiries",  '/inquiries/' %>
<%end %>

<% if session[:user_type] =="realtor"%>
  <% if @real_estate_company_id == -1 %>

   NOTE :  You have not added your company to your profile. We recommend you adding the company information to enjoy more features of our website

    <%else %>
    <br>
    <br>
    <%= link_to "Edit company information ",  edit_real_estate_company_url(@real_estate_company_id) %>
    <br>
    <br>
    <%= link_to "List a house ", '/houses/new' %>
    <br>
    <br>
    <%= link_to "View houses posted by my company ",  'houses/houses_posted_by_company' %>
    <br>
    <br>
    <%= link_to "View all inquiries for my company ",  '/inquiries/show_all_for_company' %>
    <br>
    <br>


    <%end %>
  <br>
  <br>
  <%= link_to "Edit profile ",  edit_realtor_url(session[:id]) %>


  <br>
  <br>
  <%= link_to "View all houses ", '/houses/index' %>

  <br>
  <br>
  <%= link_to "Houses posted by me ",  'houses/houses_posted_by_me' %>



<%end %>

<% if session[:user_type] =="househunter"%>

  <br>
  <%= link_to "Show real estate companies ", real_estate_companies_url%>
  <br>
  <br>
  <%= link_to "Show houses ", show_houses_with_filters_url%>
  <br>
  <br>
  <%= link_to "View my inquiries ", '/inquiries/current_user_inquiries' %>
  <br>
  <br>
  <%= link_to "My interest list",  '/houses/my_interest_list' %>
  <br>
  <br>
<%end %>

<br>
<br>
<%= link_to "Reset password ", '/users/reset_password_form'  %>

myapp/app/views/users/reset_password_form.html.erb
<%= render "banner" %>
<%= render "header" %>
<head>
  <style>
    #notice {
      color: red;
      font-size: large;
    }

  </style>
</head>
<p id="notice"> <%=notice %></p>
<%= form_with url: "/users/reset_password" , scope: :user  do |form| %>
  <p id="main">
    <%= form.label :new_password %>
    <%= form.password_field :new_password %>
    <br>
    <br>
    <%= form.label :confirm_new_password %>
    <%= form.password_field :confirm_new_password %>
    <br>
    <br>
    <%= form.label :old_password %>
    <%= form.password_field :old_password %>
    <br>
    <br>
    <%= submit_tag("Reset password") %>
    <br>
    <br>

    <br>
    <br>
    <%= link_to 'Go back to homepage', '/homepage' %> |
  </p>
<% end %>

myapp/app/views/users/show_all.html.erb
<div style="text-align:center"><h2> All users  </h2> </div>
<%= render "realtor" %>
<%= render "househunter" %>

myapp/app/views/users/sign_in.html.erb
<%= render "banner" %>

<head>
  <style>
    #notice {
      color: red;
      font-size: large;
    }
    #main {
      text-indent: 30px;
      color: darkblue;
    }
  </style>
</head>
<p id="notice"> <%=notice %></p>
<%= form_with url: "/users/check_credentials"  do |form| %>
  <p id="main">
  <%= form.label :email %>
  <%= form.text_field :email %>
  <br>
  <br>
  <%= form.label :password %>
  <%= form.password_field :password %>
  <br>

  <br>
  <%= form.radio_button :usertype, 'realtor', :checked => true %>
  <%= form.label :realtor %>
  <%= form.radio_button :usertype, 'househunter' %>
  <%= form.label :house_hunter %>
  <%= form.radio_button :usertype, 'admin'%>
  <%= form.label :admin %>
  <br>
  <br> <%= link_to "Forgot your password ? Click here to reset ", '/users/forgot_password_form' %>
    <br>
    <br>
           <%= submit_tag("Login") %>
  <br>
  <br>
  <%= link_to "Sign up as Realtor", '/realtors/new' %>
  <br>
  <br>
  <%= link_to "Sign up as House Hunter", '/house_hunters/new' %>
  </p>
<% end %>